// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ConvertPosition;
//
//    var convertPosition = ConvertPosition.FromJson(jsonString);

namespace ConvertPosition
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ConvertPosition
    {
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Data { get; set; }

        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }
    }

    public partial class ConvertPosition
    {
        public static ConvertPosition FromJson(string json) => JsonConvert.DeserializeObject<ConvertPosition>(json, ConvertPosition.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ConvertPosition self) => JsonConvert.SerializeObject(self, ConvertPosition.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
