// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using GttPlaceOrder;
//
//    var gttPlaceOrder = GttPlaceOrder.FromJson(jsonString);

namespace GttPlaceOrder
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class GttPlaceOrder
    {
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public Data Data { get; set; }

        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("trigger_id", NullValueHandling = NullValueHandling.Ignore)]
        public long? TriggerId { get; set; }
    }

    public partial class GttPlaceOrder
    {
        public static GttPlaceOrder FromJson(string json) => JsonConvert.DeserializeObject<GttPlaceOrder>(json, GttPlaceOrder.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this GttPlaceOrder self) => JsonConvert.SerializeObject(self, GttPlaceOrder.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
