// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var historicalOi = HistoricalOi.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class HistoricalOi
    {
        [JsonProperty("$ref")]
        public string Ref { get; set; }

        [JsonProperty("$schema")]
        public Uri Schema { get; set; }

        [JsonProperty("definitions")]
        public Definitions Definitions { get; set; }
    }

    public partial class Definitions
    {
        [JsonProperty("Candle")]
        public Candle Candle { get; set; }

        [JsonProperty("Data")]
        public Data Data { get; set; }

        [JsonProperty("HistoricalOi")]
        public HistoricalOiClass HistoricalOi { get; set; }
    }

    public partial class Candle
    {
        [JsonProperty("anyOf")]
        public AnyOf[] AnyOf { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }
    }

    public partial class AnyOf
    {
        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("additionalProperties")]
        public bool AdditionalProperties { get; set; }

        [JsonProperty("properties")]
        public DataProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] DataRequired { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class DataProperties
    {
        [JsonProperty("candles")]
        public Candles Candles { get; set; }
    }

    public partial class Candles
    {
        [JsonProperty("items")]
        public Items Items { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class Items
    {
        [JsonProperty("items")]
        public DataClass ItemsItems { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class DataClass
    {
        [JsonProperty("$ref")]
        public string Ref { get; set; }
    }

    public partial class HistoricalOiClass
    {
        [JsonProperty("additionalProperties")]
        public bool AdditionalProperties { get; set; }

        [JsonProperty("properties")]
        public HistoricalOiProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] HistoricalOiClassRequired { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class HistoricalOiProperties
    {
        [JsonProperty("data")]
        public DataClass Data { get; set; }

        [JsonProperty("status")]
        public AnyOf Status { get; set; }
    }

    public partial class HistoricalOi
    {
        public static HistoricalOi FromJson(string json) => JsonConvert.DeserializeObject<HistoricalOi>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this HistoricalOi self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
