// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var ltp = Ltp.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Ltp
    {
        [JsonProperty("$ref")]
        public string Ref { get; set; }

        [JsonProperty("$schema")]
        public Uri Schema { get; set; }

        [JsonProperty("definitions")]
        public Definitions Definitions { get; set; }
    }

    public partial class Definitions
    {
        [JsonProperty("Data")]
        public Data Data { get; set; }

        [JsonProperty("Ltp")]
        public LtpClass Ltp { get; set; }

        [JsonProperty("NseInfy")]
        public NseInfyClass NseInfy { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("additionalProperties")]
        public bool AdditionalProperties { get; set; }

        [JsonProperty("properties")]
        public DataProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] DataRequired { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class DataProperties
    {
        [JsonProperty("NSE:INFY")]
        public NseInfy NseInfy { get; set; }
    }

    public partial class NseInfy
    {
        [JsonProperty("$ref")]
        public string Ref { get; set; }
    }

    public partial class LtpClass
    {
        [JsonProperty("additionalProperties")]
        public bool AdditionalProperties { get; set; }

        [JsonProperty("properties")]
        public LtpProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] LtpClassRequired { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class LtpProperties
    {
        [JsonProperty("data")]
        public NseInfy Data { get; set; }

        [JsonProperty("status")]
        public Status Status { get; set; }
    }

    public partial class Status
    {
        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class NseInfyClass
    {
        [JsonProperty("additionalProperties")]
        public bool AdditionalProperties { get; set; }

        [JsonProperty("properties")]
        public NseInfyProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] NseInfyClassRequired { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class NseInfyProperties
    {
        [JsonProperty("instrument_token")]
        public Status InstrumentToken { get; set; }

        [JsonProperty("last_price")]
        public Status LastPrice { get; set; }
    }

    public partial class Ltp
    {
        public static Ltp FromJson(string json) => JsonConvert.DeserializeObject<Ltp>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Ltp self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
