// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var mfOrders = MfOrders.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class MfOrders
    {
        [JsonProperty("$ref")]
        public string Ref { get; set; }

        [JsonProperty("$schema")]
        public Uri Schema { get; set; }

        [JsonProperty("definitions")]
        public Definitions Definitions { get; set; }
    }

    public partial class Definitions
    {
        [JsonProperty("Datum")]
        public Datum Datum { get; set; }

        [JsonProperty("MFOrders")]
        public MfOrdersClass MfOrders { get; set; }
    }

    public partial class Datum
    {
        [JsonProperty("additionalProperties")]
        public bool AdditionalProperties { get; set; }

        [JsonProperty("properties")]
        public DatumProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] DatumRequired { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class DatumProperties
    {
        [JsonProperty("amount")]
        public Amount Amount { get; set; }

        [JsonProperty("average_price")]
        public Amount AveragePrice { get; set; }

        [JsonProperty("exchange_order_id")]
        public ExchangeOrderId ExchangeOrderId { get; set; }

        [JsonProperty("exchange_timestamp")]
        public ExchangeOrderId ExchangeTimestamp { get; set; }

        [JsonProperty("folio")]
        public Amount Folio { get; set; }

        [JsonProperty("fund")]
        public Amount Fund { get; set; }

        [JsonProperty("last_price")]
        public Amount LastPrice { get; set; }

        [JsonProperty("last_price_date")]
        public LastPriceDate LastPriceDate { get; set; }

        [JsonProperty("order_id")]
        public LastPriceDate OrderId { get; set; }

        [JsonProperty("order_timestamp")]
        public LastPriceDate OrderTimestamp { get; set; }

        [JsonProperty("placed_by")]
        public Amount PlacedBy { get; set; }

        [JsonProperty("purchase_type")]
        public Amount PurchaseType { get; set; }

        [JsonProperty("quantity")]
        public Amount Quantity { get; set; }

        [JsonProperty("settlement_id")]
        public ExchangeOrderId SettlementId { get; set; }

        [JsonProperty("status")]
        public Amount Status { get; set; }

        [JsonProperty("status_message")]
        public Amount StatusMessage { get; set; }

        [JsonProperty("tag")]
        public Tag Tag { get; set; }

        [JsonProperty("tradingsymbol")]
        public Amount Tradingsymbol { get; set; }

        [JsonProperty("transaction_type")]
        public Amount TransactionType { get; set; }

        [JsonProperty("variety")]
        public Amount Variety { get; set; }
    }

    public partial class Amount
    {
        [JsonProperty("type")]
        public TypeEnum Type { get; set; }
    }

    public partial class ExchangeOrderId
    {
        [JsonProperty("anyOf")]
        public LastPriceDate[] AnyOf { get; set; }
    }

    public partial class LastPriceDate
    {
        [JsonProperty("format", NullValueHandling = NullValueHandling.Ignore)]
        public string Format { get; set; }

        [JsonProperty("type")]
        public TypeEnum Type { get; set; }
    }

    public partial class Tag
    {
        [JsonProperty("anyOf")]
        public Amount[] AnyOf { get; set; }
    }

    public partial class MfOrdersClass
    {
        [JsonProperty("additionalProperties")]
        public bool AdditionalProperties { get; set; }

        [JsonProperty("properties")]
        public MfOrdersProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] MfOrdersClassRequired { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class MfOrdersProperties
    {
        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("status")]
        public Amount Status { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("items")]
        public Items Items { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class Items
    {
        [JsonProperty("$ref")]
        public string Ref { get; set; }
    }

    public enum TypeEnum { Null, Number, String };

    public partial class MfOrders
    {
        public static MfOrders FromJson(string json) => JsonConvert.DeserializeObject<MfOrders>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this MfOrders self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                TypeEnumConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class TypeEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(TypeEnum) || t == typeof(TypeEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "null":
                    return TypeEnum.Null;
                case "number":
                    return TypeEnum.Number;
                case "string":
                    return TypeEnum.String;
            }
            throw new Exception("Cannot unmarshal type TypeEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (TypeEnum)untypedValue;
            switch (value)
            {
                case TypeEnum.Null:
                    serializer.Serialize(writer, "null");
                    return;
                case TypeEnum.Number:
                    serializer.Serialize(writer, "number");
                    return;
                case TypeEnum.String:
                    serializer.Serialize(writer, "string");
                    return;
            }
            throw new Exception("Cannot marshal type TypeEnum");
        }

        public static readonly TypeEnumConverter Singleton = new TypeEnumConverter();
    }
}
