// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var mfSipPlace = MfSipPlace.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class MfSipPlace
    {
        [JsonProperty("$ref")]
        public string Ref { get; set; }

        [JsonProperty("$schema")]
        public Uri Schema { get; set; }

        [JsonProperty("definitions")]
        public Definitions Definitions { get; set; }
    }

    public partial class Definitions
    {
        [JsonProperty("Data")]
        public Data Data { get; set; }

        [JsonProperty("MFSIPPlace")]
        public MfsipPlaceClass MfsipPlace { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("additionalProperties")]
        public bool AdditionalProperties { get; set; }

        [JsonProperty("properties")]
        public DataProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] DataRequired { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class DataProperties
    {
        [JsonProperty("sip_id")]
        public Sipid SipId { get; set; }
    }

    public partial class Sipid
    {
        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class MfsipPlaceClass
    {
        [JsonProperty("additionalProperties")]
        public bool AdditionalProperties { get; set; }

        [JsonProperty("properties")]
        public MfsipPlaceProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] MfsipPlaceClassRequired { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class MfsipPlaceProperties
    {
        [JsonProperty("data")]
        public DataClass Data { get; set; }

        [JsonProperty("status")]
        public Sipid Status { get; set; }
    }

    public partial class DataClass
    {
        [JsonProperty("$ref")]
        public string Ref { get; set; }
    }

    public partial class MfSipPlace
    {
        public static MfSipPlace FromJson(string json) => JsonConvert.DeserializeObject<MfSipPlace>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this MfSipPlace self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
