// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using TickerFull;
//
//    var tickerFull = TickerFull.FromJson(jsonString);

namespace TickerFull
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class TickerFull
    {
        [JsonProperty("average_traded_price", NullValueHandling = NullValueHandling.Ignore)]
        public double? AverageTradedPrice { get; set; }

        [JsonProperty("change", NullValueHandling = NullValueHandling.Ignore)]
        public double? Change { get; set; }

        [JsonProperty("depth", NullValueHandling = NullValueHandling.Ignore)]
        public Depth Depth { get; set; }

        [JsonProperty("exchange_timestamp", NullValueHandling = NullValueHandling.Ignore)]
        public string ExchangeTimestamp { get; set; }

        [JsonProperty("instrument_token", NullValueHandling = NullValueHandling.Ignore)]
        public long? InstrumentToken { get; set; }

        [JsonProperty("last_price", NullValueHandling = NullValueHandling.Ignore)]
        public long? LastPrice { get; set; }

        [JsonProperty("last_trade_time", NullValueHandling = NullValueHandling.Ignore)]
        public string LastTradeTime { get; set; }

        [JsonProperty("last_traded_quantity", NullValueHandling = NullValueHandling.Ignore)]
        public long? LastTradedQuantity { get; set; }

        [JsonProperty("mode", NullValueHandling = NullValueHandling.Ignore)]
        public string Mode { get; set; }

        [JsonProperty("ohlc", NullValueHandling = NullValueHandling.Ignore)]
        public Ohlc Ohlc { get; set; }

        [JsonProperty("oi", NullValueHandling = NullValueHandling.Ignore)]
        public long? Oi { get; set; }

        [JsonProperty("oi_day_high", NullValueHandling = NullValueHandling.Ignore)]
        public long? OiDayHigh { get; set; }

        [JsonProperty("oi_day_low", NullValueHandling = NullValueHandling.Ignore)]
        public long? OiDayLow { get; set; }

        [JsonProperty("total_buy_quantity", NullValueHandling = NullValueHandling.Ignore)]
        public long? TotalBuyQuantity { get; set; }

        [JsonProperty("total_sell_quantity", NullValueHandling = NullValueHandling.Ignore)]
        public long? TotalSellQuantity { get; set; }

        [JsonProperty("tradable", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Tradable { get; set; }

        [JsonProperty("volume_traded", NullValueHandling = NullValueHandling.Ignore)]
        public long? VolumeTraded { get; set; }
    }

    public partial class Depth
    {
        [JsonProperty("buy", NullValueHandling = NullValueHandling.Ignore)]
        public Buy[] Buy { get; set; }

        [JsonProperty("sell", NullValueHandling = NullValueHandling.Ignore)]
        public Buy[] Sell { get; set; }
    }

    public partial class Buy
    {
        [JsonProperty("orders", NullValueHandling = NullValueHandling.Ignore)]
        public long? Orders { get; set; }

        [JsonProperty("price", NullValueHandling = NullValueHandling.Ignore)]
        public long? Price { get; set; }

        [JsonProperty("quantity", NullValueHandling = NullValueHandling.Ignore)]
        public long? Quantity { get; set; }
    }

    public partial class Ohlc
    {
        [JsonProperty("close", NullValueHandling = NullValueHandling.Ignore)]
        public long? Close { get; set; }

        [JsonProperty("high", NullValueHandling = NullValueHandling.Ignore)]
        public long? High { get; set; }

        [JsonProperty("low", NullValueHandling = NullValueHandling.Ignore)]
        public long? Low { get; set; }

        [JsonProperty("open", NullValueHandling = NullValueHandling.Ignore)]
        public long? Open { get; set; }
    }

    public partial class TickerFull
    {
        public static TickerFull[] FromJson(string json) => JsonConvert.DeserializeObject<TickerFull[]>(json, TickerFull.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this TickerFull[] self) => JsonConvert.SerializeObject(self, TickerFull.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
