// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var trades = Trades.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Trades
    {
        [JsonProperty("$ref")]
        public string Ref { get; set; }

        [JsonProperty("$schema")]
        public Uri Schema { get; set; }

        [JsonProperty("definitions")]
        public Definitions Definitions { get; set; }
    }

    public partial class Definitions
    {
        [JsonProperty("Datum")]
        public Datum Datum { get; set; }

        [JsonProperty("Trades")]
        public TradesClass Trades { get; set; }
    }

    public partial class Datum
    {
        [JsonProperty("additionalProperties")]
        public bool AdditionalProperties { get; set; }

        [JsonProperty("properties")]
        public DatumProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] DatumRequired { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class DatumProperties
    {
        [JsonProperty("average_price")]
        public AveragePrice AveragePrice { get; set; }

        [JsonProperty("exchange")]
        public AveragePrice Exchange { get; set; }

        [JsonProperty("exchange_order_id")]
        public AveragePrice ExchangeOrderId { get; set; }

        [JsonProperty("exchange_timestamp")]
        public ExchangeTimestamp ExchangeTimestamp { get; set; }

        [JsonProperty("fill_timestamp")]
        public ExchangeTimestamp FillTimestamp { get; set; }

        [JsonProperty("instrument_token")]
        public AveragePrice InstrumentToken { get; set; }

        [JsonProperty("order_id")]
        public AveragePrice OrderId { get; set; }

        [JsonProperty("order_timestamp")]
        public ExchangeTimestamp OrderTimestamp { get; set; }

        [JsonProperty("product")]
        public AveragePrice Product { get; set; }

        [JsonProperty("quantity")]
        public AveragePrice Quantity { get; set; }

        [JsonProperty("trade_id")]
        public ExchangeTimestamp TradeId { get; set; }

        [JsonProperty("tradingsymbol")]
        public AveragePrice Tradingsymbol { get; set; }

        [JsonProperty("transaction_type")]
        public AveragePrice TransactionType { get; set; }
    }

    public partial class AveragePrice
    {
        [JsonProperty("type")]
        public TypeEnum Type { get; set; }
    }

    public partial class ExchangeTimestamp
    {
        [JsonProperty("format")]
        public string Format { get; set; }

        [JsonProperty("type")]
        public TypeEnum Type { get; set; }
    }

    public partial class TradesClass
    {
        [JsonProperty("additionalProperties")]
        public bool AdditionalProperties { get; set; }

        [JsonProperty("properties")]
        public TradesProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] TradesClassRequired { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class TradesProperties
    {
        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("status")]
        public AveragePrice Status { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("items")]
        public Items Items { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class Items
    {
        [JsonProperty("$ref")]
        public string Ref { get; set; }
    }

    public enum TypeEnum { Integer, Number, String };

    public partial class Trades
    {
        public static Trades FromJson(string json) => JsonConvert.DeserializeObject<Trades>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Trades self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                TypeEnumConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class TypeEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(TypeEnum) || t == typeof(TypeEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "integer":
                    return TypeEnum.Integer;
                case "number":
                    return TypeEnum.Number;
                case "string":
                    return TypeEnum.String;
            }
            throw new Exception("Cannot unmarshal type TypeEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (TypeEnum)untypedValue;
            switch (value)
            {
                case TypeEnum.Integer:
                    serializer.Serialize(writer, "integer");
                    return;
                case TypeEnum.Number:
                    serializer.Serialize(writer, "number");
                    return;
                case TypeEnum.String:
                    serializer.Serialize(writer, "string");
                    return;
            }
            throw new Exception("Cannot marshal type TypeEnum");
        }

        public static readonly TypeEnumConverter Singleton = new TypeEnumConverter();
    }
}
