// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using TriggerRange;
//
//    var triggerRange = TriggerRange.FromJson(jsonString);

namespace TriggerRange
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class TriggerRange
    {
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, Datum> Data { get; set; }

        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }
    }

    public partial class Datum
    {
        [JsonProperty("instrument_token", NullValueHandling = NullValueHandling.Ignore)]
        public long? InstrumentToken { get; set; }

        [JsonProperty("lower", NullValueHandling = NullValueHandling.Ignore)]
        public double? Lower { get; set; }

        [JsonProperty("upper", NullValueHandling = NullValueHandling.Ignore)]
        public double? Upper { get; set; }
    }

    public partial class TriggerRange
    {
        public static TriggerRange FromJson(string json) => JsonConvert.DeserializeObject<TriggerRange>(json, TriggerRange.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this TriggerRange self) => JsonConvert.SerializeObject(self, TriggerRange.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
